from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]


def get_dashboard_data() -> dict:
    return {
        "branding": {
            "companyName": "SentinelIQ",
            "logoFile": "SentinelIQ logo with modern design.png",
            "tagline": "AI-powered video intelligence for safer spaces",
        },
        "summary": [
            {"label": "Active Cameras", "value": "12"},
            {"label": "Anomalies Today", "value": "17"},
            {"label": "Avg Confidence", "value": "94%"},
            {"label": "Analyst Queue", "value": "4"},
        ],
        "tips": [
            "Focus review on clips above 85% anomaly score.",
            "Use severity filters to reduce alert fatigue.",
            "Export validated incidents for retraining later.",
        ],
        "heroStats": [
            {"label": "Model online", "kind": "live"},
            {"label": "Latency 142 ms", "kind": "default"},
            {"label": "2 cameras need attention", "kind": "warning"},
        ],
        "tabs": [
            {
                "id": "live",
                "label": "Live Monitoring",
                "pageTitle": "Real-time anomaly detection dashboard",
                "heroKicker": "Now monitoring Warehouse Zone A",
                "heroTitle": "Surface unusual activity quickly without overwhelming the operator.",
                "heroBody": "This interface prioritizes fast scanning: live feed first, context second, and review actions directly where decisions happen.",
            },
            {
                "id": "review",
                "label": "Incident Review",
                "pageTitle": "Incident review workspace",
                "heroKicker": "Analyst queue for validated clips",
                "heroTitle": "Move from AI flag to operator decision with evidence and notes in one place.",
                "heroBody": "The review screen helps analysts verify clips quickly, log reasoning, and route confirmed incidents into escalation and retraining flows.",
            },
            {
                "id": "health",
                "label": "Camera Health",
                "pageTitle": "Camera health dashboard",
                "heroKicker": "Hardware and stream quality at a glance",
                "heroTitle": "Catch blind spots before they become security gaps.",
                "heroBody": "Operators and admins can see offline cameras, image quality drift, and network issues without leaving the surveillance workspace.",
            },
            {
                "id": "insights",
                "label": "Model Insights",
                "pageTitle": "Model insights and feedback",
                "heroKicker": "Performance trends across locations",
                "heroTitle": "Track how the detector behaves in the field and where it needs help.",
                "heroBody": "This view shows class mix, feedback quality, and drift indicators so your team can improve the model with real operating data.",
            },
            {
                "id": "settings",
                "label": "Settings",
                "pageTitle": "Operational settings",
                "heroKicker": "Thresholds and notification examples",
                "heroTitle": "Tune the system without exposing operators to unnecessary complexity.",
                "heroBody": "Settings can be grouped into clear, policy-based controls so teams can adjust sensitivity, escalation, and retraining rules safely.",
            },
        ],
        "alerts": [
            {
                "title": "Fence climbing at north perimeter",
                "camera": "Camera 04",
                "meta": "2 min ago",
                "risk": "91%",
                "riskClass": "high",
                "videoFile": "fence.mp4",
                "label": "Perimeter breach",
                "count": "1 flagged subject",
                "badge": "High Risk",
                "badgeClass": "high",
                "box": {"top": 28, "left": 56, "width": 19, "height": 32},
                "objectType": "Person",
                "suggestedAction": "Dispatch patrol",
            },
            {
                "title": "Aggressive interaction in parking area",
                "camera": "Camera 09",
                "meta": "6 min ago",
                "risk": "84%",
                "riskClass": "medium",
                "videoFile": "Bully.mp4",
                "label": "Possible assault",
                "count": "2 flagged subjects",
                "badge": "Medium Risk",
                "badgeClass": "medium",
                "box": {"top": 34, "left": 42, "width": 26, "height": 30},
                "objectType": "Two people",
                "suggestedAction": "Escalate to security",
            },
            {
                "title": "After-hours hallway movement",
                "camera": "Camera 02",
                "meta": "11 min ago",
                "risk": "79%",
                "riskClass": "medium",
                "videoFile": "hallway.mp4",
                "label": "After-hours movement",
                "count": "1 flagged subject",
                "badge": "Medium Risk",
                "badgeClass": "medium",
                "box": {"top": 26, "left": 51, "width": 18, "height": 36},
                "objectType": "Person",
                "suggestedAction": "Verify badge access",
            },
            {
                "title": "Graffiti activity near south wall",
                "camera": "Camera 07",
                "meta": "18 min ago",
                "risk": "73%",
                "riskClass": "low",
                "videoFile": "graffiti.mp4",
                "label": "Property damage",
                "count": "1 flagged subject",
                "badge": "Low Risk",
                "badgeClass": "low",
                "box": {"top": 30, "left": 58, "width": 22, "height": 34},
                "objectType": "Person",
                "suggestedAction": "Review and preserve evidence",
            },
        ],
        "cameraFleet": [
            {"name": "Camera 04", "location": "Loading Dock North", "status": "Healthy", "statusClass": "ok"},
            {"name": "Camera 09", "location": "Visitor Parking", "status": "Blur detected", "statusClass": "warn"},
            {"name": "Camera 02", "location": "South Corridor", "status": "Healthy", "statusClass": "ok"},
            {"name": "Camera 11", "location": "Storage Room B", "status": "Offline 3 min", "statusClass": "warn"},
        ],
        "modelMetrics": [
            {"label": "Precision", "value": "92%", "width": 92},
            {"label": "Recall", "value": "88%", "width": 88},
            {"label": "False Positive Rate", "value": "14%", "width": 14},
        ],
        "reviewQueue": [
            {"clip": "Clip 2418", "camera": "Camera 04", "duration": "14 seconds", "risk": "91%", "riskClass": "high"},
            {"clip": "Clip 2415", "camera": "Camera 09", "duration": "22 seconds", "risk": "84%", "riskClass": "medium"},
            {"clip": "Clip 2408", "camera": "Camera 02", "duration": "9 seconds", "risk": "79%", "riskClass": "medium"},
        ],
        "reviewNotes": [
            {"label": "Context", "value": "Subject remained inside restricted loading zone for 43 seconds after vehicle departure."},
            {"label": "Reason flagged", "value": "Loitering pattern exceeded learned baseline for this area and time window."},
            {"label": "Recommended workflow", "value": "Review clip, confirm policy breach, notify site security, and save for retraining set."},
        ],
        "reviewTimeline": [
            {"time": "00:02", "text": "Subject exits vehicle and remains in zone."},
            {"time": "00:09", "text": "Trajectory slows below expected threshold."},
            {"time": "00:14", "text": "Anomaly score crosses review threshold."},
        ],
        "healthCards": [
            {"label": "Warehouse", "value": "5 / 5 online", "text": "No packet loss in the last hour."},
            {"label": "Parking", "value": "3 / 4 online", "text": "Camera 11 offline, failover pending."},
            {"label": "Corridors", "value": "4 / 4 online", "text": "Camera 09 needs lens cleaning."},
        ],
        "maintenanceFlags": [
            {"title": "Camera 09", "text": "Focus drift detected at 03:02 PM. Suggested maintenance within 24 hours."},
            {"title": "Camera 11", "text": "Stream dropped 3 times in 20 minutes. Check switch port and power."},
            {"title": "Camera 03", "text": "Night contrast trending down 12% over 7 days."},
        ],
        "uptimeRows": [
            {"camera": "Camera 04", "uptime": "99.8%", "bandwidth": "6.2 Mbps", "issue": "No issues"},
            {"camera": "Camera 09", "uptime": "97.9%", "bandwidth": "5.8 Mbps", "issue": "Blur alert 1 hour ago"},
            {"camera": "Camera 11", "uptime": "91.4%", "bandwidth": "0.0 Mbps", "issue": "Offline now"},
        ],
        "driftNotes": [
            {"label": "Parking zone", "value": "False positives rose 6% after lighting change near entrance."},
            {"label": "Night shift corridor", "value": "Recall improved after adding 214 validated movement clips."},
            {"label": "Recommendation", "value": "Retrain with more rain and glare conditions before site-wide rollout."},
        ],
        "classDistribution": [
            {"label": "Loitering", "value": "46%", "width": 46},
            {"label": "Vehicle dwell", "value": "24%", "width": 24},
            {"label": "After-hours entry", "value": "18%", "width": 18},
            {"label": "Abandoned object", "value": "12%", "width": 12},
        ],
        "feedbackRows": [
            {"source": "Warehouse", "confirmed": "31", "falsePositive": "4", "ready": "Yes"},
            {"source": "Parking", "confirmed": "19", "falsePositive": "9", "ready": "Needs review"},
            {"source": "Corridors", "confirmed": "14", "falsePositive": "2", "ready": "Yes"},
        ],
        "settings": [
            {"label": "Anomaly review threshold", "value": "0.82"},
            {"label": "Minimum dwell time", "value": "12 sec"},
            {"label": "Alert cooldown", "value": "90 sec"},
        ],
        "notificationRules": [
            {"label": "High risk", "value": "Send SMS and dashboard alert immediately."},
            {"label": "Medium risk", "value": "Add to operator queue and email shift lead."},
            {"label": "Low risk", "value": "Log only unless repeated 3 times in 10 minutes."},
        ],
    }
